<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="44022" started-at="2019-06-26T20:07:51Z" finished-at="2019-06-26T20:08:35Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="44022" started-at="2019-06-26T20:07:51Z" finished-at="2019-06-26T20:08:35Z">
      <class name="TestCases.tests.test">
        <test-method status="PASS" signature="start()[pri:0, instance:TestCases.tests.test@59a6e353]" name="start" is-config="true" duration-ms="16899" started-at="2019-06-27T01:37:51Z" finished-at="2019-06-27T01:38:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="FAIL" signature="LogOut()[pri:4, instance:TestCases.tests.test@59a6e353]" name="LogOut" duration-ms="18745" started-at="2019-06-27T01:38:07Z" finished-at="2019-06-27T01:38:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.gojek.utilities.Log.endTestCase(Log.java:40)
	at com.gojek.utilities.Log.fail(Log.java:55)
	at com.gojek.pageObjects.LogOutPage.clickLogOut(LogOutPage.java:56)
	at TestCases.tests.test.LogOut(test.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogOut -->
        <test-method status="PASS" signature="close()[pri:0, instance:TestCases.tests.test@59a6e353]" name="close" is-config="true" duration-ms="8368" started-at="2019-06-27T01:38:26Z" finished-at="2019-06-27T01:38:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- TestCases.tests.test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
